# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Rust Toolchain
    before: |
      echo "Install Rustup"
      #curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
      echo "Setting Rust toolchain"
      #rustup default stable
      #rustup target list --installed
      #rustup target add wasm32-unknown-unknown
      CARGO_HOME=/home/gitpod/.cargo rustup install nightly
      rustup target add wasm32-unknown-unknown --toolchain nightly
      rustup default nightly
      #echo "Install build essentials"
      #sudo apt install build-essential
      gp sync-done toolchain
      # echo "Compile"
      # cargo wasm
      # RUST_BACKTRACE=1 cargo unit-test
      # cargo integration-test
      # cargo schema

  - name: SecretDev Local Blockchain
    before: docker pull enigmampc/secret-network-sw-dev
    init: gp sync-await toolchain
    command: |
      echo "Starting secretdev local blockchain"

      
  - name: Install Vue
    init: |
      gp sync-await toolchain
    command: |
      echo "Install Vue"
      yarn global add @vue/cli
      gp sync-done vue

  - name: Dependencies and Dev Server
    init: gp sync-await vue
    command: |
      cd app
      echo "Install dependencies"
      yarn install 
      yarn dev

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
