# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Install Vue CLI
    before:
    command: yarn global add @vue/cli
    onOpen: split-right

  - name: Dependencies and Dev Server
    init: |
      cd app
      yarn install 
    command: yarn dev
    onOpen: split-right

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
