# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before:
    command: echo "Start secretdev local blockchain"

  - init: 
      yarn global add @vue/cli
      cd app
      yarn install 

  - name: Run Dev Server
    command:
      cd app
      yarn dev

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
