# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: | # runs during prebuild
      cd app; npm install 
  - name: Dev Server
    command: |
      echo "Start dev server"
      cd app; pwd; npm run dev
  - name: New Terminal
    command: echo "New terminal window!"

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

