# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Rust Toolchain
    before: |
      echo "Rust toolchain"
      CARGO_HOME=/home/gitpod/.cargo rustup install nightly
      rustup target add wasm32-unknown-unknown --toolchain nightly
      rustup default nightly
    init: gp sync-done toolchain
    command: exit

  - name: Install Vue
    before: |
      echo "Install Vue"
      yarn global add @vue/cli
    init: |
      gp sync-await toolchain
      gp sync-done vue
    command: exit
    openMode: split-right

  - name: Compile and Run Unit Tests
    before: docker pull enigmampc/secret-contract-optimizer:latest
    init: |
      gp sync-await toolchain
      echo "Compile secret contract"
      cd contracts
      cargo wasm
      echo "Run unit tests"
      RUST_BACKTRACE=1 cargo unit-test
      echo "Run contract optimizer"
      docker run --rm -v "$(pwd)":/contract \
        --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
        --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
        enigmampc/secret-contract-optimizer 
      gp sync-done compile
    openMode: split-right

  - name: SecretDev Local Blockchain
    before: docker pull ghcr.io/scrtlabs/localsecret:latest
    init: gp sync-await compile
    command: |
      echo "Starting secretdev local blockchain"
      cd contracts
      docker run -it --rm -p 9091:9091 -p 26657:26657 -p 1317:1317 -p 5000:5000 -v $(pwd):/root/code --name localsecret ghcr.io/scrtlabs/localsecret
      sleep 10
      gp sync-done blockchain
      docker container logs -f secretdev
    openMode: split-right

  - name: Secret Contract Deploy and Instantiate
    command: |
      gp sync-await blockchain
      cd contracts
      sleep 5
      echo "Deploy secret contract to local blockchain"
      docker exec -w /root/code -it secretdev scripts/deploy.sh
      sleep 5
      echo "Instantiate secret contract"
      docker exec -w /root/code -it secretdev scripts/instantiate.sh
      sleep 5
      echo "Get contract address"
      docker exec -w /root/code -it secretdev scripts/get_address.sh
      gp sync-done secretcontract
    openMode: split-right
      
  - name: Dependencies and Dev Server
    init: gp sync-await vue
    command: |
      gp sync-await secretcontract
      cd app
      echo "Install dependencies"
      yarn install 
      yarn dev
    openMode: split-right

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
